var AI_LIST = [
  { "ai": "02", "label": "GTIN of contained trade items" },
  { "ai": "11", "label": "Production date (YYMMDD)" },
  { "ai": "12", "label": "Due date (YYMMDD)" },
  { "ai": "13", "label": "Packaging date (YYMMDD)" },
  { "ai": "15", "label": "Best before date (YYMMDD)" },
  { "ai": "16", "label": "Sell by date (YYMMDD)" },
  { "ai": "17", "label": "Expiration date (YYMMDD)" },
  { "ai": "20", "label": "Internal product variant" },
  { "ai": "240", "label": "Additional product identification assigned by the manufacturer" },
  { "ai": "241", "label": "Customer part number" },
  { "ai": "242", "label": "Made-to-Order variation number" },
  { "ai": "243", "label": "Packaging component number" },
  { "ai": "250", "label": "Secondary serial number" },
  { "ai": "251", "label": "Reference to source entity" },
  { "ai": "30", "label": "Variable count of items (variable measure trade item)" },
  { "ai": "3100", "label": "Net weight, kilograms (variable measure trade item)" },
  { "ai": "3101", "label": "Net weight, kilograms (variable measure trade item)" },
  { "ai": "3102", "label": "Net weight, kilograms (variable measure trade item)" },
  { "ai": "3103", "label": "Net weight, kilograms (variable measure trade item)" },
  { "ai": "3104", "label": "Net weight, kilograms (variable measure trade item)" },
  { "ai": "3105", "label": "Net weight, kilograms (variable measure trade item)" },
  { "ai": "3110", "label": "Length or first dimension, metres (variable measure trade item)" },
  { "ai": "3111", "label": "Length or first dimension, metres (variable measure trade item)" },
  { "ai": "3112", "label": "Length or first dimension, metres (variable measure trade item)" },
  { "ai": "3113", "label": "Length or first dimension, metres (variable measure trade item)" },
  { "ai": "3114", "label": "Length or first dimension, metres (variable measure trade item)" },
  { "ai": "3115", "label": "Length or first dimension, metres (variable measure trade item)" },
  { "ai": "3120", "label": "Width, diameter, or second dimension, metres (variable measure trade item)" },
  { "ai": "3121", "label": "Width, diameter, or second dimension, metres (variable measure trade item)" },
  { "ai": "3122", "label": "Width, diameter, or second dimension, metres (variable measure trade item)" },
  { "ai": "3123", "label": "Width, diameter, or second dimension, metres (variable measure trade item)" },
  { "ai": "3124", "label": "Width, diameter, or second dimension, metres (variable measure trade item)" },
  { "ai": "3125", "label": "Width, diameter, or second dimension, metres (variable measure trade item)" },
  { "ai": "3130", "label": "Depth, thickness, height, or third dimension, metres (variable measure trade item)" },
  { "ai": "3131", "label": "Depth, thickness, height, or third dimension, metres (variable measure trade item)" },
  { "ai": "3132", "label": "Depth, thickness, height, or third dimension, metres (variable measure trade item)" },
  { "ai": "3133", "label": "Depth, thickness, height, or third dimension, metres (variable measure trade item)" },
  { "ai": "3134", "label": "Depth, thickness, height, or third dimension, metres (variable measure trade item)" },
  { "ai": "3135", "label": "Depth, thickness, height, or third dimension, metres (variable measure trade item)" },
  { "ai": "3140", "label": "Area, square metres (variable measure trade item)" },
  { "ai": "3141", "label": "Area, square metres (variable measure trade item)" },
  { "ai": "3142", "label": "Area, square metres (variable measure trade item)" },
  { "ai": "3143", "label": "Area, square metres (variable measure trade item)" },
  { "ai": "3144", "label": "Area, square metres (variable measure trade item)" },
  { "ai": "3145", "label": "Area, square metres (variable measure trade item)" },
  { "ai": "3150", "label": "Net volume, litres (variable measure trade item)" },
  { "ai": "3151", "label": "Net volume, litres (variable measure trade item)" },
  { "ai": "3152", "label": "Net volume, litres (variable measure trade item)" },
  { "ai": "3153", "label": "Net volume, litres (variable measure trade item)" },
  { "ai": "3154", "label": "Net volume, litres (variable measure trade item)" },
  { "ai": "3155", "label": "Net volume, litres (variable measure trade item)" },
  { "ai": "3160", "label": "Net volume, cubic metres (variable measure trade item)" },
  { "ai": "3161", "label": "Net volume, cubic metres (variable measure trade item)" },
  { "ai": "3162", "label": "Net volume, cubic metres (variable measure trade item)" },
  { "ai": "3163", "label": "Net volume, cubic metres (variable measure trade item)" },
  { "ai": "3164", "label": "Net volume, cubic metres (variable measure trade item)" },
  { "ai": "3165", "label": "Net volume, cubic metres (variable measure trade item)" },
  { "ai": "3200", "label": "Net weight, pounds (variable measure trade item)" },
  { "ai": "3201", "label": "Net weight, pounds (variable measure trade item)" },
  { "ai": "3202", "label": "Net weight, pounds (variable measure trade item)" },
  { "ai": "3203", "label": "Net weight, pounds (variable measure trade item)" },
  { "ai": "3204", "label": "Net weight, pounds (variable measure trade item)" },
  { "ai": "3205", "label": "Net weight, pounds (variable measure trade item)" },
  { "ai": "3210", "label": "Length or first dimension, inches (variable measure trade item)" },
  { "ai": "3211", "label": "Length or first dimension, inches (variable measure trade item)" },
  { "ai": "3212", "label": "Length or first dimension, inches (variable measure trade item)" },
  { "ai": "3213", "label": "Length or first dimension, inches (variable measure trade item)" },
  { "ai": "3214", "label": "Length or first dimension, inches (variable measure trade item)" },
  { "ai": "3215", "label": "Length or first dimension, inches (variable measure trade item)" },
  { "ai": "3220", "label": "Length or first dimension, feet (variable measure trade item)" },
  { "ai": "3221", "label": "Length or first dimension, feet (variable measure trade item)" },
  { "ai": "3222", "label": "Length or first dimension, feet (variable measure trade item)" },
  { "ai": "3223", "label": "Length or first dimension, feet (variable measure trade item)" },
  { "ai": "3224", "label": "Length or first dimension, feet (variable measure trade item)" },
  { "ai": "3225", "label": "Length or first dimension, feet (variable measure trade item)" },
  { "ai": "3230", "label": "Length or first dimension, yards (variable measure trade item)" },
  { "ai": "3231", "label": "Length or first dimension, yards (variable measure trade item)" },
  { "ai": "3232", "label": "Length or first dimension, yards (variable measure trade item)" },
  { "ai": "3233", "label": "Length or first dimension, yards (variable measure trade item)" },
  { "ai": "3234", "label": "Length or first dimension, yards (variable measure trade item)" },
  { "ai": "3235", "label": "Length or first dimension, yards (variable measure trade item)" },
  { "ai": "3240", "label": "Width, diameter, or second dimension, inches (variable measure trade item)" },
  { "ai": "3241", "label": "Width, diameter, or second dimension, inches (variable measure trade item)" },
  { "ai": "3242", "label": "Width, diameter, or second dimension, inches (variable measure trade item)" },
  { "ai": "3243", "label": "Width, diameter, or second dimension, inches (variable measure trade item)" },
  { "ai": "3244", "label": "Width, diameter, or second dimension, inches (variable measure trade item)" },
  { "ai": "3245", "label": "Width, diameter, or second dimension, inches (variable measure trade item)" },
  { "ai": "3250", "label": "Width, diameter, or second dimension, feet (variable measure trade item)" },
  { "ai": "3251", "label": "Width, diameter, or second dimension, feet (variable measure trade item)" },
  { "ai": "3252", "label": "Width, diameter, or second dimension, feet (variable measure trade item)" },
  { "ai": "3253", "label": "Width, diameter, or second dimension, feet (variable measure trade item)" },
  { "ai": "3254", "label": "Width, diameter, or second dimension, feet (variable measure trade item)" },
  { "ai": "3255", "label": "Width, diameter, or second dimension, feet (variable measure trade item)" },
  { "ai": "3260", "label": "Width, diameter, or second dimension, yards (variable measure trade item)" },
  { "ai": "3261", "label": "Width, diameter, or second dimension, yards (variable measure trade item)" },
  { "ai": "3262", "label": "Width, diameter, or second dimension, yards (variable measure trade item)" },
  { "ai": "3263", "label": "Width, diameter, or second dimension, yards (variable measure trade item)" },
  { "ai": "3264", "label": "Width, diameter, or second dimension, yards (variable measure trade item)" },
  { "ai": "3265", "label": "Width, diameter, or second dimension, yards (variable measure trade item)" },
  { "ai": "3270", "label": "Depth, thickness, height, or third dimension, inches (variable measure trade item)" },
  { "ai": "3271", "label": "Depth, thickness, height, or third dimension, inches (variable measure trade item)" },
  { "ai": "3272", "label": "Depth, thickness, height, or third dimension, inches (variable measure trade item)" },
  { "ai": "3273", "label": "Depth, thickness, height, or third dimension, inches (variable measure trade item)" },
  { "ai": "3274", "label": "Depth, thickness, height, or third dimension, inches (variable measure trade item)" },
  { "ai": "3275", "label": "Depth, thickness, height, or third dimension, inches (variable measure trade item)" },
  { "ai": "3280", "label": "Depth, thickness, height, or third dimension, feet (variable measure trade item)" },
  { "ai": "3281", "label": "Depth, thickness, height, or third dimension, feet (variable measure trade item)" },
  { "ai": "3282", "label": "Depth, thickness, height, or third dimension, feet (variable measure trade item)" },
  { "ai": "3283", "label": "Depth, thickness, height, or third dimension, feet (variable measure trade item)" },
  { "ai": "3284", "label": "Depth, thickness, height, or third dimension, feet (variable measure trade item)" },
  { "ai": "3285", "label": "Depth, thickness, height, or third dimension, feet (variable measure trade item)" },
  { "ai": "3290", "label": "Depth, thickness, height, or third dimension, yards (variable measure trade item)" },
  { "ai": "3291", "label": "Depth, thickness, height, or third dimension, yards (variable measure trade item)" },
  { "ai": "3292", "label": "Depth, thickness, height, or third dimension, yards (variable measure trade item)" },
  { "ai": "3293", "label": "Depth, thickness, height, or third dimension, yards (variable measure trade item)" },
  { "ai": "3294", "label": "Depth, thickness, height, or third dimension, yards (variable measure trade item)" },
  { "ai": "3295", "label": "Depth, thickness, height, or third dimension, yards (variable measure trade item)" },
  { "ai": "3300", "label": "Logistic weight, kilograms" },
  { "ai": "3301", "label": "Logistic weight, kilograms" },
  { "ai": "3302", "label": "Logistic weight, kilograms" },
  { "ai": "3303", "label": "Logistic weight, kilograms" },
  { "ai": "3304", "label": "Logistic weight, kilograms" },
  { "ai": "3305", "label": "Logistic weight, kilograms" },
  { "ai": "3310", "label": "Length or first dimension, metres" },
  { "ai": "3311", "label": "Length or first dimension, metres" },
  { "ai": "3312", "label": "Length or first dimension, metres" },
  { "ai": "3313", "label": "Length or first dimension, metres" },
  { "ai": "3314", "label": "Length or first dimension, metres" },
  { "ai": "3315", "label": "Length or first dimension, metres" },
  { "ai": "3320", "label": "Width, diameter, or second dimension, metres" },
  { "ai": "3321", "label": "Width, diameter, or second dimension, metres" },
  { "ai": "3322", "label": "Width, diameter, or second dimension, metres" },
  { "ai": "3323", "label": "Width, diameter, or second dimension, metres" },
  { "ai": "3324", "label": "Width, diameter, or second dimension, metres" },
  { "ai": "3325", "label": "Width, diameter, or second dimension, metres" },
  { "ai": "3330", "label": "Depth, thickness, height, or third dimension, metres" },
  { "ai": "3331", "label": "Depth, thickness, height, or third dimension, metres" },
  { "ai": "3332", "label": "Depth, thickness, height, or third dimension, metres" },
  { "ai": "3333", "label": "Depth, thickness, height, or third dimension, metres" },
  { "ai": "3334", "label": "Depth, thickness, height, or third dimension, metres" },
  { "ai": "3335", "label": "Depth, thickness, height, or third dimension, metres" },
  { "ai": "3340", "label": "Area, square metres" },
  { "ai": "3341", "label": "Area, square metres" },
  { "ai": "3342", "label": "Area, square metres" },
  { "ai": "3343", "label": "Area, square metres" },
  { "ai": "3344", "label": "Area, square metres" },
  { "ai": "3345", "label": "Area, square metres" },
  { "ai": "3350", "label": "Logistic volume, litres" },
  { "ai": "3351", "label": "Logistic volume, litres" },
  { "ai": "3352", "label": "Logistic volume, litres" },
  { "ai": "3353", "label": "Logistic volume, litres" },
  { "ai": "3354", "label": "Logistic volume, litres" },
  { "ai": "3355", "label": "Logistic volume, litres" },
  { "ai": "3360", "label": "Logistic volume, cubic metres" },
  { "ai": "3361", "label": "Logistic volume, cubic metres" },
  { "ai": "3362", "label": "Logistic volume, cubic metres" },
  { "ai": "3363", "label": "Logistic volume, cubic metres" },
  { "ai": "3364", "label": "Logistic volume, cubic metres" },
  { "ai": "3365", "label": "Logistic volume, cubic metres" },
  { "ai": "3370", "label": "Kilograms per square metre" },
  { "ai": "3371", "label": "Kilograms per square metre" },
  { "ai": "3372", "label": "Kilograms per square metre" },
  { "ai": "3373", "label": "Kilograms per square metre" },
  { "ai": "3374", "label": "Kilograms per square metre" },
  { "ai": "3375", "label": "Kilograms per square metre" },
  { "ai": "3400", "label": "Logistic weight, pounds" },
  { "ai": "3401", "label": "Logistic weight, pounds" },
  { "ai": "3402", "label": "Logistic weight, pounds" },
  { "ai": "3403", "label": "Logistic weight, pounds" },
  { "ai": "3404", "label": "Logistic weight, pounds" },
  { "ai": "3405", "label": "Logistic weight, pounds" },
  { "ai": "3410", "label": "Length or first dimension, inches" },
  { "ai": "3411", "label": "Length or first dimension, inches" },
  { "ai": "3412", "label": "Length or first dimension, inches" },
  { "ai": "3413", "label": "Length or first dimension, inches" },
  { "ai": "3414", "label": "Length or first dimension, inches" },
  { "ai": "3415", "label": "Length or first dimension, inches" },
  { "ai": "3420", "label": "Length or first dimension, feet" },
  { "ai": "3421", "label": "Length or first dimension, feet" },
  { "ai": "3422", "label": "Length or first dimension, feet" },
  { "ai": "3423", "label": "Length or first dimension, feet" },
  { "ai": "3424", "label": "Length or first dimension, feet" },
  { "ai": "3425", "label": "Length or first dimension, feet" },
  { "ai": "3430", "label": "Length or first dimension, yards" },
  { "ai": "3431", "label": "Length or first dimension, yards" },
  { "ai": "3432", "label": "Length or first dimension, yards" },
  { "ai": "3433", "label": "Length or first dimension, yards" },
  { "ai": "3434", "label": "Length or first dimension, yards" },
  { "ai": "3435", "label": "Length or first dimension, yards" },
  { "ai": "3440", "label": "Width, diameter, or second dimension, inches" },
  { "ai": "3441", "label": "Width, diameter, or second dimension, inches" },
  { "ai": "3442", "label": "Width, diameter, or second dimension, inches" },
  { "ai": "3443", "label": "Width, diameter, or second dimension, inches" },
  { "ai": "3444", "label": "Width, diameter, or second dimension, inches" },
  { "ai": "3445", "label": "Width, diameter, or second dimension, inches" },
  { "ai": "3450", "label": "Width, diameter, or second dimension, feet" },
  { "ai": "3451", "label": "Width, diameter, or second dimension, feet" },
  { "ai": "3452", "label": "Width, diameter, or second dimension, feet" },
  { "ai": "3453", "label": "Width, diameter, or second dimension, feet" },
  { "ai": "3454", "label": "Width, diameter, or second dimension, feet" },
  { "ai": "3455", "label": "Width, diameter, or second dimension, feet" },
  { "ai": "3460", "label": "Width, diameter, or second dimension, yard" },
  { "ai": "3461", "label": "Width, diameter, or second dimension, yard" },
  { "ai": "3462", "label": "Width, diameter, or second dimension, yard" },
  { "ai": "3463", "label": "Width, diameter, or second dimension, yard" },
  { "ai": "3464", "label": "Width, diameter, or second dimension, yard" },
  { "ai": "3465", "label": "Width, diameter, or second dimension, yard" },
  { "ai": "3470", "label": "Depth, thickness, height, or third dimension, inches" },
  { "ai": "3471", "label": "Depth, thickness, height, or third dimension, inches" },
  { "ai": "3472", "label": "Depth, thickness, height, or third dimension, inches" },
  { "ai": "3473", "label": "Depth, thickness, height, or third dimension, inches" },
  { "ai": "3474", "label": "Depth, thickness, height, or third dimension, inches" },
  { "ai": "3475", "label": "Depth, thickness, height, or third dimension, inches" },
  { "ai": "3480", "label": "Depth, thickness, height, or third dimension, feet" },
  { "ai": "3481", "label": "Depth, thickness, height, or third dimension, feet" },
  { "ai": "3482", "label": "Depth, thickness, height, or third dimension, feet" },
  { "ai": "3483", "label": "Depth, thickness, height, or third dimension, feet" },
  { "ai": "3484", "label": "Depth, thickness, height, or third dimension, feet" },
  { "ai": "3485", "label": "Depth, thickness, height, or third dimension, feet" },
  { "ai": "3490", "label": "Depth, thickness, height, or third dimension, yards" },
  { "ai": "3491", "label": "Depth, thickness, height, or third dimension, yards" },
  { "ai": "3492", "label": "Depth, thickness, height, or third dimension, yards" },
  { "ai": "3493", "label": "Depth, thickness, height, or third dimension, yards" },
  { "ai": "3494", "label": "Depth, thickness, height, or third dimension, yards" },
  { "ai": "3495", "label": "Depth, thickness, height, or third dimension, yards" },
  { "ai": "3500", "label": "Area, square inches (variable measure trade item)" },
  { "ai": "3501", "label": "Area, square inches (variable measure trade item)" },
  { "ai": "3502", "label": "Area, square inches (variable measure trade item)" },
  { "ai": "3503", "label": "Area, square inches (variable measure trade item)" },
  { "ai": "3504", "label": "Area, square inches (variable measure trade item)" },
  { "ai": "3505", "label": "Area, square inches (variable measure trade item)" },
  { "ai": "3510", "label": "Area, square feet (variable measure trade item)" },
  { "ai": "3511", "label": "Area, square feet (variable measure trade item)" },
  { "ai": "3512", "label": "Area, square feet (variable measure trade item)" },
  { "ai": "3513", "label": "Area, square feet (variable measure trade item)" },
  { "ai": "3514", "label": "Area, square feet (variable measure trade item)" },
  { "ai": "3515", "label": "Area, square feet (variable measure trade item)" },
  { "ai": "3520", "label": "Area, square yards (variable measure trade item)" },
  { "ai": "3521", "label": "Area, square yards (variable measure trade item)" },
  { "ai": "3522", "label": "Area, square yards (variable measure trade item)" },
  { "ai": "3523", "label": "Area, square yards (variable measure trade item)" },
  { "ai": "3524", "label": "Area, square yards (variable measure trade item)" },
  { "ai": "3525", "label": "Area, square yards (variable measure trade item)" },
  { "ai": "3530", "label": "Area, square inches" },
  { "ai": "3531", "label": "Area, square inches" },
  { "ai": "3532", "label": "Area, square inches" },
  { "ai": "3533", "label": "Area, square inches" },
  { "ai": "3534", "label": "Area, square inches" },
  { "ai": "3535", "label": "Area, square inches" },
  { "ai": "3540", "label": "Area, square feet" },
  { "ai": "3541", "label": "Area, square feet" },
  { "ai": "3542", "label": "Area, square feet" },
  { "ai": "3543", "label": "Area, square feet" },
  { "ai": "3544", "label": "Area, square feet" },
  { "ai": "3545", "label": "Area, square feet" },
  { "ai": "3550", "label": "Area, square yards" },
  { "ai": "3551", "label": "Area, square yards" },
  { "ai": "3552", "label": "Area, square yards" },
  { "ai": "3553", "label": "Area, square yards" },
  { "ai": "3554", "label": "Area, square yards" },
  { "ai": "3555", "label": "Area, square yards" },
  { "ai": "3560", "label": "Net weight, troy ounces (variable measure trade item)" },
  { "ai": "3561", "label": "Net weight, troy ounces (variable measure trade item)" },
  { "ai": "3562", "label": "Net weight, troy ounces (variable measure trade item)" },
  { "ai": "3563", "label": "Net weight, troy ounces (variable measure trade item)" },
  { "ai": "3564", "label": "Net weight, troy ounces (variable measure trade item)" },
  { "ai": "3565", "label": "Net weight, troy ounces (variable measure trade item)" },
  { "ai": "3570", "label": "Net weight (or volume), ounces (variable measure trade item)" },
  { "ai": "3571", "label": "Net weight (or volume), ounces (variable measure trade item)" },
  { "ai": "3572", "label": "Net weight (or volume), ounces (variable measure trade item)" },
  { "ai": "3573", "label": "Net weight (or volume), ounces (variable measure trade item)" },
  { "ai": "3574", "label": "Net weight (or volume), ounces (variable measure trade item)" },
  { "ai": "3575", "label": "Net weight (or volume), ounces (variable measure trade item)" },
  { "ai": "3600", "label": "Net volume, quarts (variable measure trade item)" },
  { "ai": "3601", "label": "Net volume, quarts (variable measure trade item)" },
  { "ai": "3602", "label": "Net volume, quarts (variable measure trade item)" },
  { "ai": "3603", "label": "Net volume, quarts (variable measure trade item)" },
  { "ai": "3604", "label": "Net volume, quarts (variable measure trade item)" },
  { "ai": "3605", "label": "Net volume, quarts (variable measure trade item)" },
  { "ai": "3610", "label": "Net volume, gallons U.S. (variable measure trade item)" },
  { "ai": "3611", "label": "Net volume, gallons U.S. (variable measure trade item)" },
  { "ai": "3612", "label": "Net volume, gallons U.S. (variable measure trade item)" },
  { "ai": "3613", "label": "Net volume, gallons U.S. (variable measure trade item)" },
  { "ai": "3614", "label": "Net volume, gallons U.S. (variable measure trade item)" },
  { "ai": "3615", "label": "Net volume, gallons U.S. (variable measure trade item)" },
  { "ai": "3620", "label": "Logistic volume, quarts" },
  { "ai": "3621", "label": "Logistic volume, quarts" },
  { "ai": "3622", "label": "Logistic volume, quarts" },
  { "ai": "3623", "label": "Logistic volume, quarts" },
  { "ai": "3624", "label": "Logistic volume, quarts" },
  { "ai": "3625", "label": "Logistic volume, quarts" },
  { "ai": "3630", "label": "Logistic volume, gallons U.S." },
  { "ai": "3631", "label": "Logistic volume, gallons U.S." },
  { "ai": "3632", "label": "Logistic volume, gallons U.S." },
  { "ai": "3633", "label": "Logistic volume, gallons U.S." },
  { "ai": "3634", "label": "Logistic volume, gallons U.S." },
  { "ai": "3635", "label": "Logistic volume, gallons U.S." },
  { "ai": "3640", "label": "Net volume, cubic inches (variable measure trade item)" },
  { "ai": "3641", "label": "Net volume, cubic inches (variable measure trade item)" },
  { "ai": "3642", "label": "Net volume, cubic inches (variable measure trade item)" },
  { "ai": "3643", "label": "Net volume, cubic inches (variable measure trade item)" },
  { "ai": "3644", "label": "Net volume, cubic inches (variable measure trade item)" },
  { "ai": "3645", "label": "Net volume, cubic inches (variable measure trade item)" },
  { "ai": "3650", "label": "Net volume, cubic feet (variable measure trade item)" },
  { "ai": "3651", "label": "Net volume, cubic feet (variable measure trade item)" },
  { "ai": "3652", "label": "Net volume, cubic feet (variable measure trade item)" },
  { "ai": "3653", "label": "Net volume, cubic feet (variable measure trade item)" },
  { "ai": "3654", "label": "Net volume, cubic feet (variable measure trade item)" },
  { "ai": "3655", "label": "Net volume, cubic feet (variable measure trade item)" },
  { "ai": "3660", "label": "Net volume, cubic yards (variable measure trade item)" },
  { "ai": "3661", "label": "Net volume, cubic yards (variable measure trade item)" },
  { "ai": "3662", "label": "Net volume, cubic yards (variable measure trade item)" },
  { "ai": "3663", "label": "Net volume, cubic yards (variable measure trade item)" },
  { "ai": "3664", "label": "Net volume, cubic yards (variable measure trade item)" },
  { "ai": "3665", "label": "Net volume, cubic yards (variable measure trade item)" },
  { "ai": "3670", "label": "Logistic volume, cubic inches" },
  { "ai": "3671", "label": "Logistic volume, cubic inches" },
  { "ai": "3672", "label": "Logistic volume, cubic inches" },
  { "ai": "3673", "label": "Logistic volume, cubic inches" },
  { "ai": "3674", "label": "Logistic volume, cubic inches" },
  { "ai": "3675", "label": "Logistic volume, cubic inches" },
  { "ai": "3680", "label": "Logistic volume, cubic feet" },
  { "ai": "3681", "label": "Logistic volume, cubic feet" },
  { "ai": "3682", "label": "Logistic volume, cubic feet" },
  { "ai": "3683", "label": "Logistic volume, cubic feet" },
  { "ai": "3684", "label": "Logistic volume, cubic feet" },
  { "ai": "3685", "label": "Logistic volume, cubic feet" },
  { "ai": "3690", "label": "Logistic volume, cubic yards" },
  { "ai": "3691", "label": "Logistic volume, cubic yards" },
  { "ai": "3692", "label": "Logistic volume, cubic yards" },
  { "ai": "3693", "label": "Logistic volume, cubic yards" },
  { "ai": "3694", "label": "Logistic volume, cubic yards" },
  { "ai": "3695", "label": "Logistic volume, cubic yards" },
  { "ai": "37", "label": "Count of trade items" },
  { "ai": "3900", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3901", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3902", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3903", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3904", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3905", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3906", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3907", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3908", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3909", "label": "Applicable amount payable or Coupon value, local currency" },
  { "ai": "3910", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3911", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3912", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3913", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3914", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3915", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3916", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3917", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3918", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3919", "label": "Applicable amount payable with ISO currency code" },
  { "ai": "3920", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3921", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3922", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3923", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3924", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3925", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3926", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3927", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3928", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3929", "label": "Applicable amount payable, single monetary area (variable measure trade item)" },
  { "ai": "3930", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3931", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3932", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3933", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3934", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3935", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3936", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3937", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3938", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3939", "label": "Applicable amount payable with ISO currency code (variable measure trade item)" },
  { "ai": "3940", "label": "Percentage discount of a coupon" },
  { "ai": "3941", "label": "Percentage discount of a coupon" },
  { "ai": "3942", "label": "Percentage discount of a coupon" },
  { "ai": "3943", "label": "Percentage discount of a coupon" },
  { "ai": "400", "label": "Customer's purchase order number" },
  { "ai": "403", "label": "Routing code" },
  { "ai": "410", "label": "Ship to - Deliver to Global Location Number" },
  { "ai": "411", "label": "Bill to - Invoice to Global Location Number" },
  { "ai": "412", "label": "Purchased from Global Location Number" },
  { "ai": "413", "label": "Ship for - Deliver for - Forward to Global Location Number" },
  { "ai": "416", "label": "GLN of the production or service location" },
  { "ai": "420", "label": "Ship to - Deliver to postal code within a single postal authority" },
  { "ai": "421", "label": "Ship to - Deliver to postal code with ISO country code" },
  { "ai": "422", "label": "Country of origin of a trade item" },
  { "ai": "423", "label": "Country of initial processing" },
  { "ai": "424", "label": "Country of processing" },
  { "ai": "425", "label": "Country of disassembly" },
  { "ai": "426", "label": "Country covering full process chain" },
  { "ai": "427", "label": "Country subdivision Of origin" },
  { "ai": "7001", "label": "NATO Stock Number (NSN)" },
  { "ai": "7002", "label": "UN/ECE meat carcasses and cuts classification" },
  { "ai": "7003", "label": "Expiration date and time" },
  { "ai": "7004", "label": "Active potency" },
  { "ai": "7005", "label": "Catch area" },
  { "ai": "7006", "label": "First freeze date" },
  { "ai": "7007", "label": "Harvest date" },
  { "ai": "7008", "label": "Species for fishery purposes" },
  { "ai": "7009", "label": "Fishing gear type" },
  { "ai": "7010", "label": "Production method" },
  { "ai": "7020", "label": "Refurbishment lot ID" },
  { "ai": "7021", "label": "Functional status" },
  { "ai": "7022", "label": "Revision status" },
  { "ai": "7023", "label": "Global Individual Asset Identifier (GIAI) of an assembly" },
  { "ai": "7030", "label": "Number of processor with ISO Country Code" },
  { "ai": "7031", "label": "Number of processor with ISO Country Code" },
  { "ai": "7032", "label": "Number of processor with ISO Country Code" },
  { "ai": "7033", "label": "Number of processor with ISO Country Code" },
  { "ai": "7034", "label": "Number of processor with ISO Country Code" },
  { "ai": "7035", "label": "Number of processor with ISO Country Code" },
  { "ai": "7036", "label": "Number of processor with ISO Country Code" },
  { "ai": "7037", "label": "Number of processor with ISO Country Code" },
  { "ai": "7038", "label": "Number of processor with ISO Country Code" },
  { "ai": "7039", "label": "Number of processor with ISO Country Code" },
  { "ai": "710", "label": "National Healthcare Reimbursement Number (NHRN) - Germany PZN" },
  { "ai": "711", "label": "National Healthcare Reimbursement Number (NHRN) - France CIP" },
  { "ai": "712", "label": "National Healthcare Reimbursement Number (NHRN) - Spain CN" },
  { "ai": "713", "label": "National Healthcare Reimbursement Number (NHRN) - Brasil DRN" },
  { "ai": "714", "label": "National Healthcare Reimbursement Number (NHRN) - Portugal AIM" },
  { "ai": "8001", "label": "Roll products (width, length, core diameter, direction, splices)" },
  { "ai": "8002", "label": "Cellular mobile telephone identifier" },
  { "ai": "8007", "label": "International Bank Account Number (IBAN)" },
  { "ai": "8008", "label": "Date and time of production" },
  { "ai": "8012", "label": "Software version" },
  { "ai": "8013", "label": "Global Model Number (GMN)" },
  { "ai": "8020", "label": "Payment slip reference number" },
  { "ai": "8110", "label": "Coupon code identification for use in North America" },
  { "ai": "8111", "label": "Loyalty points of a coupon" },
  { "ai": "8112", "label": "Paperless coupon code identification for use in North America" },
  { "ai": "8200", "label": "Extended Packaging URL" },
  { "ai": "90", "label": "Information mutually agreed between trading partners" },
  { "ai": "91", "label": "Company internal information" },
  { "ai": "92", "label": "Company internal information" },
  { "ai": "93", "label": "Company internal information" },
  { "ai": "94", "label": "Company internal information" },
  { "ai": "95", "label": "Company internal information" },
  { "ai": "96", "label": "Company internal information" },
  { "ai": "97", "label": "Company internal information" },
  { "ai": "98", "label": "Company internal information" },
  { "ai": "99", "label": "Company internal information" }
];